- name: Configure Git user name for the new user
  become_user: "{{ new_user }}"
  git_config:
    name: user.name
    value: "{{ git_user_name }}"
    scope: global

- name: Configure Git user email for the new user
  become_user: "{{ new_user }}"
  git_config:
    name: user.email
    value: "{{ git_user_email }}"
    scope: global