- name: Update package list
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: dist
    autoremove: yes

- name: Install essential packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - binwalk
    - bmon
    - btop
    - build-essential
    - chisel
    - dirbuster
    - dkms
    - foremost
    - gobuster
    - htop
    - hydra
    - john
    - netcat-traditional
    - nikto
    - nmap
    - openvpn
    - proxychains
    - rlwrap
    - socat
    - sqlmap
    - tmux
    - virtualbox-guest-utils
    - virtualbox-guest-x11
    - wpscan

- name: Get the current kernel version
  command: uname -r
  register: kernel_version
  changed_when: false

- name: Install Python packages
  pip:
    name: "{{ item }}"
  with_items:
    - pwntools
    - requests
    - impacket
    - kerbrute